# site settings
title: SKIPAB2
subtitle: 
email: idkskipab2@gmail.com
description: An enginner who wants a better world
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city:
state: 
zip_code:
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/SKIPAB2
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/hyeonjo_o_o/?hl=en
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/profile.php?id=100006925809718
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
